apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: <YOUR_NAMESPACE>
  name: prometheus-service
spec:
  replicas: 1
  scrapeInterval: 5s
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: <YOUR_NAMESPACE>
  serviceMonitorSelector:
    matchLabels:
      prometheus: <YOUR_NAMESPACE>

