apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: <YOUR_NAMESPACE>
  name: app-service-monitor
spec:
  endpoints:
  - path: /metrics
    port: http
  selector:
    ## Service Selector Labels of your app
    matchLabels:
      prometheus: <YOUR_NAMESPACE>
